blank_issues_enabled: false
contact_links:
  - name: Diskusi umum
    url: https://github.com/sad25kag/BetbetMiro-Extension/discussions
    about: Gunakan Discussions untuk obrolan umum, request santai, atau pertanyaan non-bug.
